target 'tencent-broadcast'
platform :ios, '11.0'
pod 'VideoCast', :git => 'https://github.com/cats-oss/VideoCast-Swift.git'
pod 'SwiftLint'
pod 'TXLiteAVSDK_Professional'
pod 'GPUImage', :git => 'https://github.com/BradLarson/GPUImage.git'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'AFNetworking', '~> 3.0'
pod 'ZipArchive'
use_frameworks!
